apiVersion: conventions.carto.run/v1alpha1
kind: PodIntent
metadata:
  name: podintent-sample
spec:
  serviceAccountName: controller-manager
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: workload
        image: ubuntu:bionic
        command:
        - env
